version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - VAULT_ADDR=http://vaultcontainer:8200
      - VAULT_TOKEN=root
    depends_on:
      - vault
    networks:
      - internalnet

  vault:
    image: vault:1.13.3
    container_name: vaultcontainer
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    volumes:
      - vault_data:/vault/data
    cap_add:
      - IPC_LOCK
    restart: always
    command: server -dev
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge

volumes:
  vault_data: